version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
